#! /usr/bin/env bash

#
# ngroker, a tiny helper for launching ngrok sessions with my colleagues.
# Requires jq, jl and ngrok:
#
#   brew install jq jl ngrok
#
#   DEBUG=1 to enable some debugging,
#   COLOR=(never|always) to turn on/off coloring and emojis.
#
# Note: you can also use gh-auth to allow your colleagues to access your
# session using by allowing their pub key stored on Github.
#
#    gem install github-auth
#    gh-auth add --users=gumbi2400 --command="/usr/local/bin/tmux attach"
#    gh-auth add --users="maelvls" --command="/usr/local/bin/tmux attach"

# Turn on coloring only if the current shell is interactive (or COLOR=always)
if [ -t 1 ] || [ "$COLOR" = always ] && [ "$COLOR" != never ]; then
    gray='\033[90m'
    red='\033[91m'
    blue='\033[94m'
    green='\033[92m'
    yel='\033[93m'
    end='\033[0m'
    ok='✅ '
    warn='⚠️  '
    err='❌ '
fi

if ! command -v jl >/dev/null 2>&1; then
    echo "${err}${red}Error:${end} jl not found, install it with:" >&2
    echo "    ${gray}(cd && GO111MODULE=on go get github.com/koenbollen/jl)${end}" >&2
    exit 13
fi

if ! command -v ngrok >/dev/null 2>&1; then
    echo "${err}${red}Error:${end} ngrok not found, install it with:" >&2
    echo "    ${gray}brew cask install ngrok${end}" >&2
    exit 14
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "${err}${red}Error:${end} ngrok not found, install it with:" >&2
    echo "    ${gray}brew install jq${end}" >&2
    exit 14
fi

ngrok tcp 22 --region=eu --log=stdout --log-format=json | tee >(jl >/dev/stderr) | while read -r line; do
    if url=$(echo "$line" | jq --exit-status -r '.url'); then
        port=$(echo "$url" | cut -d: -f3)
        host=$(echo "$url" | cut -d: -f2 | tr -d '/')
        [ -z "$DEBUG" ] || echo -e "url found: $yel$url$end"
        [ -z "$DEBUG" ] || echo -e "port found: $yel$port$end"
        [ -z "$DEBUG" ] || echo -e "host found: $yel$host$end"

        cmd="ssh $USER@$host -p $port"

        echo -e "${ok}${green}Note:${end} here is the command to paste in Slack: ${gray}(already copied into paste-bin)${end}"
        echo -e "    $blue$cmd$end"
        echo "$cmd" | pbcopy
        echo -e "${warn}${yel}Warning:${end} don't forget to also ${yel}gh-auth add${end}:"
        echo -e "    ${gray}gh-auth add --command='/usr/local/bin/tmux attach' --users=Callisto13${end}"
    fi
done
